layout_spectrum: 0.016129
color:
  saturation: 0.4433773
  lightness: 0.3388318
  brandStrength: 0.4969656
  rhythmicContrast: 0.4082599
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.8549535
name: 'Urbantouch Wedding '
